[package]
name = "dmfr-dataset-reader"
version = "0.2.5"
edition = "2024"
description = "Reads transitland folder and outputs graph of valid feeds and operators"
license = "AGPL-3.0-or-later"

[dependencies]
dmfr = "0.2.2"
serde = "1.0"
serde_json = "1.0"
